### ISSUE TITLE
Data Augmentation

### ISSUE THREAD

**Issue by Ivamcoder** [3d-hand-shape/hand-graph-cnn#10]
Hi @3d-hand-shape 
Thanks in advance for your helpful comments
Have you had data augmentation (random rotation translation of image and 3D labels) during training,  as I found in data loader provided for evaluation not any specific augmentation, is this data loader used for training too?

**Comment by 3d-hand-shape** [comment]
Yes, we did data augmentation during training. This data loader is only used for evaluation.

**Comment by Ivamcoder** [comment]
For rotation , after rotating the image, you change the 3D annotation or camera parameter ?
