### ISSUE TITLE
 data augmentation

### ISSUE THREAD

**Issue by Ivamcoder** [3d-hand-shape/hand-graph-cnn#11]
@3d-hand-shape  For rotation , after rotating the image, you change the 3D annotation or camera parameter ?

_Originally posted by @Ivamcoder in https://github.com/3d-hand-shape/hand-graph-cnn/issues/10#issuecomment-508368394_

**Comment by 3d-hand-shape** [comment]
Yes, we rotate the image and the 3D annotation at the same time.
