### ISSUE TITLE
Definition of Snap Joint

### ISSUE THREAD

**Issue by prismformore** [3d-hand-shape/hand-graph-cnn#13]
https://github.com/3d-hand-shape/hand-graph-cnn/blob/8980ebb88c196bf0d37bd4bd57304475c18c82eb/hand_shape_pose/data/dataset/STB_dataset.py#L63

May I know what is ``Snap Joint'' and why do we need to convert the STB index to Snap index? Is ``Snap joint'' given by the synthetic dataset collected by your team?
Thank you.

**Comment by 3d-hand-shape** [comment]
Yes, 'Snap joints' are defined by our synthetic dataset.
