### ISSUE TITLE
Can't download the pre-train model.

### ISSUE THREAD

**Issue by zhaojianxin** [3d-hand-shape/hand-graph-cnn#14]
I can't get the pre-train model by this link,https://mega.nz/#!yfZXBayC!izaLXi4X8LsgPuRWqKlUrCKBWNLVKTvfgAuFIS7SSFY.I don;t kown how to deal with it.I will look for ward your reply and help me .Thank you.

**Comment by prismformore** [comment]
I met the same problem. This is a Big Fire Work issue.

**Comment by prismformore** [comment]
> I can't get the pre-train model by this link,https://mega.nz/#!yfZXBayC!izaLXi4X8LsgPuRWqKlUrCKBWNLVKTvfgAuFIS7SSFY.I don;t kown how to deal with it.I will look for ward your reply and help me .Thank you.

I met the same problem. This is a Big Fire Work issue. @zhaojianxin

**Comment by 3d-hand-shape** [comment]
We have uploaded the pre-trained models to Github. Pls check the latest update.
