### ISSUE TITLE
How to get the GT boxes? 

### ISSUE THREAD

**Issue by prismformore** [3d-hand-shape/hand-graph-cnn#17]
How to get the GT boxes? Thank you. @Ivamcoder @3d-hand-shape

_Originally posted by @prismformore in https://github.com/3d-hand-shape/hand-graph-cnn/issues/8#issuecomment-515824332_

**Comment by afawa** [comment]
I have the same problem, and now I try to use openpose to generate the crop boxes. @prismformore

**Comment by 3d-hand-shape** [comment]
Thank @afawa for your comment. You can train a hand detector to get the bounding box of hand.
