### ISSUE TITLE
Cannot install opendr properly, does it crucial for training? or it is just for visualization?

### ISSUE THREAD

**Issue by WenqiangX** [3d-hand-shape/hand-graph-cnn#18]
Hi, guys

I find it is difficult to install opendr properly (I tried with anaconda python2, pip install, but failed).
I wonder if it is crucial for training? or it is just for visualization?

Thanks.

**Comment by WangChengLongWilliam** [comment]
https://github.com/polmorenoc/opendr 希望能帮上你 @WenqiangX

**Comment by 3d-hand-shape** [comment]
Thank @WilliamWang1994  for providing the answer!
Opendr is not crucial for training if you do not add depth supervision in the training.

**Comment by hanyutan** [comment]
> https://github.com/polmorenoc/opendr 希望能帮上你 @WenqiangX

@WilliamWang1994 Thx for the answer! I installed opendr successfully and found that it's version0.73. Does it matter when the requirements.txt mentions >=0.76?
