### ISSUE TITLE
How could I calculate pose_root?

### ISSUE THREAD

**Issue by HUTHG** [3d-hand-shape/hand-graph-cnn#19]
Hi I am trying to implementing your pre-trained model on wild images, I noticed that cam_parameters & pose_roots are read from params.mat. May I know how could you calculate the pose_root?

Best
Tian

**Comment by KobayashiLiu** [comment]
hello,did u solve this problem?
I found that in forward function the root joint's xyz position is from ground truth.

**Comment by KobayashiLiu** [comment]
> 
> 
> Hi I am trying to implementing your pre-trained model on wild images, I noticed that cam_parameters & pose_roots are read from params.mat. May I know how could you calculate the pose_root?
> 
> Best
> Tian

hello,did u solve this problem?
I found that in forward function the root joint's xyz position is from ground truth.

**Comment by 3d-hand-shape** [comment]
Yes, the mesh/pose depth generated by the network is relative to the root joint and scale-invariant. So we need to use the depth of root joint, camera intrinsic parameters, and hand scale to recover the absolute 3D mesh/pose.
In real applications, you can train another neural network to predict the root joint depth and hand scale.

**Comment by nfsergiu** [comment]
@3d-hand-shape what do you mean by "hand scale" in this context? I see it is set to 5 for every image in the dataset. What does it represent?

**Comment by thunder95** [comment]
@3d-hand-shape how to generate the root joints and pose scales from my own real-word-image-data?
