### ISSUE TITLE
Are cam_params, pose_root and pose scale must be known?

### ISSUE THREAD

**Issue by CalciferZh** [3d-hand-shape/hand-graph-cnn#20]
Or is there a default setting so that the system can run on **pure** color input without any other information? Thank you very much.

**Comment by CalciferZh** [comment]
I found setting cam_params to some default value works fine, the z value of pose root is also okay to be default, but x and y of pose_root must be known and cannot be predicted. Is that correct?

**Comment by CalciferZh** [comment]
I think that's because the provided code cannot regress wrist coordinates from the predicted mesh.

**Comment by VinhDuong10998** [comment]
i  have issue same your question, i don't know pose_root and bbox value when run my image, i think run hand detection in my image to get bbox but pose_root don't know

**Comment by siriusdemon** [comment]
Hi, I am new to this field and I wonder what's the meaning of camera parameters. I found it is a 4-element vector like this: 
```
tensor([[923.6480, 923.7590, 640.0470, 362.3360],
        [923.6480, 923.7590, 640.0470, 362.3360],
        [923.6480, 923.7590, 640.0470, 362.3360],
        [923.6480, 923.7590, 640.0470, 362.3360],
        [923.6480, 923.7590, 640.0470, 362.3360],
        [923.6480, 923.7590, 640.0470, 362.3360],
        [923.6480, 923.7590, 640.0470, 362.3360],
        [923.6480, 923.7590, 640.0470, 362.3360]])
```
Can you help me ? Thanks in advance! @vinhdc10998 @3d-hand-shape @CalciferZh
