### ISSUE TITLE
evaluating on RHD

### ISSUE THREAD

**Issue by Ivamcoder** [3d-hand-shape/hand-graph-cnn#21]
Hi @geliuhao ,

The reported `AUC` on `RHD` dataset, How you treat both hands in one image, did you consider both available hands in images for training and testing or have you chosen the more dominant hand from each image?

**Comment by 3d-hand-shape** [comment]
We just followed the code released by the ICCV'17 paper "Learning to estimate 3d hand pose from single RGB images" (https://lmb.informatik.uni-freiburg.de/projects/hand3d/), in which they choose the hand that has more pixels in the image according to the hand mask.
