### ISSUE TITLE
How to run on GPU

### ISSUE THREAD

**Issue by ihewro** [3d-hand-shape/hand-graph-cnn#24]
*eval_real_world_testset.yaml*
![image](https://user-images.githubusercontent.com/20165605/68597416-e2eec500-04d7-11ea-8297-8b308121c29f.png)

*eval_script.py*
![image](https://user-images.githubusercontent.com/20165605/68597489-0285ed80-04d8-11ea-8b40-c0c52f882aca.png)

*real_world_testset.py*
![image](https://user-images.githubusercontent.com/20165605/68597576-29dcba80-04d8-11ea-9cf4-3a43a96bdbad.png)

I changed the code as above, but I couldn't run  the project

I get the errors:

```
RuntimeError: CUDA error: out of memory 
```

or

```
Killed
```

![image](https://user-images.githubusercontent.com/20165605/68597626-42e56b80-04d8-11ea-8cb7-a4f7e456c1c1.png)

can you give me some help 

Be deeply grateful!

My machine information：

Tesla P100-PCIE

**Comment by u0251077** [comment]
how to solve?

**Comment by ArashHosseini** [comment]
@ihewro check [fork](https://github.com/ArashHosseini/hand-graph-cnn-gpu) pls, gpu eval is implemented there, cheers
