### ISSUE TITLE
Model not rendered

### ISSUE THREAD

**Issue by PascalYIN** [3d-hand-shape/hand-graph-cnn#25]
Hello ! 
First of all congratulations for your great jobs !
I tried to run the eval_script.py with exactly the same command lines of your tutorial, but the evaluated shape is not rendered on the images saved by the script. I checked the output of the mesh rendering step, and got a bunch of 0 in the rendered images. 
I'm wandering if this is because of incorrect requirements' versions, but I'm not quite sure about this. So by the way, what are the exact requirements version of your code ? It seems that your pkl file are saved with python3, while opendr 0.76 do not support installations with python3.

Being grateful while waiting for your response !

**Comment by 3d-hand-shape** [comment]
I suggest you use Opendr>=0.76 and Python 2.7.

**Comment by sunshineZXJ** [comment]
I have the same question. Have you solved this problem?

**Comment by PascalYIN** [comment]
@sunshineZXJ Hello, I wouldn't say that I have solved the problem, but I actually did get a rendered result. If you are using PyCharm I suggest that you dig a little bit deeper in the code and try to save the rendered images before they are overplayed onto the input RGB images. You will see that it do have rendered the hand shape model. 

It has been a while that I stopped working on this demo, but if I remembered correctly, you can start with [this line](https://github.com/3d-hand-shape/hand-graph-cnn/blob/a2ebaff9988f7c9963dc593df77d557194669158/hand_shape_pose/util/vis.py#L176), where rend_img_vp1 and rend_img_vp2 are two rendered images of the hand shape without background. Save them with the correct data format (uint8) and normally you well see the rendered results.
