### ISSUE TITLE
How to write to obj file

### ISSUE THREAD

**Issue by FighterFong** [3d-hand-shape/hand-graph-cnn#26]
Hi,Author
I was complete test my own image,and i have a question that how to write the hand mesh to obj file according to the (8, 954, 3) vertices? how to generate vt and f? Can you help me,Thanks.

**Comment by 3d-hand-shape** [comment]
Hi, obj file is a text file. You can follow this definition of obj file https://en.wikipedia.org/wiki/Wavefront_.obj_file to write 3D coordinates of vertices into the obj file. `vt` defines the texture, `f` defines the edges of the polygon. You can keep `vt` and `f` the same as those in the template file ./data/0214_lowP_vn_g.0001.obj.
