### ISSUE TITLE
How to install the module "Opendr" ?

### ISSUE THREAD

**Issue by junsang7777** [3d-hand-shape/hand-graph-cnn#28]
it is impossible that "setup.py" is not working

**Comment by bianfangzhou** [comment]
你好，opendr安装失败这个问题您解决了吗

**Comment by SightVanish** [comment]
> 你好，opendr安装失败这个问题您解决了吗

opendr is only compatible with python2
https://stackoverflow.com/questions/64969585/not-able-to-install-opendr-in-python-3-6-error-in-visual-studio-libs
