### ISSUE TITLE
Real-world-dataset 3d shape ground truth

### ISSUE THREAD

**Issue by kallianisawesome** [3d-hand-shape/hand-graph-cnn#29]
Hi, I can't fins 3d hand mesh of your real-world-dataset in /data/real_world_testset, Can I have access to these files?
Thanks!

**Comment by 3d-hand-shape** [comment]
Pls follow the instruction in https://github.com/3d-hand-shape/hand-graph-cnn/tree/master/data/real_world_testset/real_hand_3D_mesh to download the ground truth 3D hand mesh.
