### ISSUE TITLE
Will this project add any other functionality, such as providing a function to test an RGB image at will？

### ISSUE THREAD

**Issue by MLsmaller** [3d-hand-shape/hand-graph-cnn#3]
I am looking forward to your reply.

**Comment by tfederico** [comment]
any update?

**Comment by tfederico** [comment]
Any update regarding this? @3d-hand-shape @geliuhao @raingo

**Comment by 3d-hand-shape** [comment]
This release is just to reproduce the results in the paper, so the function you mentioned is not supported. You are welcome to contribute.
