### ISSUE TITLE
MLP network

### ISSUE THREAD

**Issue by tedkuo1268** [3d-hand-shape/hand-graph-cnn#33]
For the full model you used to train the MLP network, is that the model fine-tuned with STB dataset or the model just trained with synthetic dataset?
Thanks in advance.

**Comment by 3d-hand-shape** [comment]
In this repo, we released both models: [the model just trained with the synthetic dataset](https://github.com/3d-hand-shape/hand-graph-cnn/tree/master/model/pretrained_models) and [the model fine-tuned with STB dataset](https://github.com/3d-hand-shape/hand-graph-cnn/tree/master/model/STB_finetuned_models).
