### ISSUE TITLE
error when loading state_dict for Net_HM_HG

### ISSUE THREAD

**Issue by DecenWill** [3d-hand-shape/hand-graph-cnn#4]
RuntimeError: Error(s) in loading state_dict for Net_HM_HG:
	Missing key(s) in state_dict: "bn1.num_batches_tracked", "r1.bn.num_batches_tracked", "r1.bn1.num_batches_tracked", "r1.bn2.num_batches_tracked", "r4.bn.num_batches_tracked", "r4.bn1.num_batches_tracked", "r4.bn2.num_batches_tracked", "r5.bn.num_batches_tracked", "r5.bn1.num_batches_tracked", "r5.bn2.num_batches_tracked", "hourglass.0.low2.low2.low2.low2_.0.bn.num_batches_tracked", "hourglass.0.low2.low2.low2.low2_.0.bn1.num_batches_tracked", "hourglass.0.low2.low2.low2.low2_.0.bn2.num_batches_tracked", "hourglass.0.low2.low2.low2.low2_.1.bn.num_batches_tracked", "hourglass.0.low2.low2.low2.low2_.1.bn1.num_batches_tracked"

How could I fix it?

**Comment by 3d-hand-shape** [comment]
Which version of Pytorch are you using? You may use the old version of Pytorch. There are two solution:
1) change to the version >= 1.0.0
2) remove these keys before loading the network. You can follow this link: https://discuss.pytorch.org/t/unexpected-key-in-state-dict-bn1-num-batches-tracked/29454/2
