### ISSUE TITLE
pose_root

### ISSUE THREAD

**Issue by yangtao19920109** [3d-hand-shape/hand-graph-cnn#41]
Thanks for your amazing idea,I train a YOLOv4 model to detect hand and  want to run your project using a USB camera,But I don't known how to feed a value pose_root,can you explain how to calculate this value?

**Comment by 3d-hand-shape** [comment]
In this paper, to get the absolute 3D hand pose and mesh, we need to know the 3D coordinate of the root joint, which can be predicted by the 3D hand detection from the entire image at test time.
