### ISSUE TITLE
error when python eval_script.py

### ISSUE THREAD

**Issue by recoverjun** [3d-hand-shape/hand-graph-cnn#5]
in net_util.py
line 86:y=torch.mm(W,x)
RuntTimeError:expected 'mat1' to be a CPU tensor,but got a CUDA tensor

**Comment by lqql2012** [comment]
I have the same error ...

**Comment by lqql2012** [comment]
i met same error, Did you solved it?

**Comment by Learningm** [comment]
I met similar errors.
The same line, y=torch.mm(W,x) in net_util.py,
RuntimeError: Expected object of type torch.sparse.FloatTensor but found type torch.cuda.sparse.FloatTensor for argument #4 'mat1'

running under the environment of python 2.7, pytorch 0.4.0, cuda 8.0.

**Comment by 3d-hand-shape** [comment]
We have fixed this bug in our latest commits. Now we support testing on cpu or gpu devices. Thanks!
