### ISSUE TITLE
Question on STB preprocessing

### ISSUE THREAD

**Issue by Ivamcoder** [3d-hand-shape/hand-graph-cnn#7]
Hi @raingo ,
Thanks for your great paper,
Thank you so much in advance

>> As it is mentioned in `STB`  readme, we have GT coordinate in `world coordinate system`,right?,  and provided `rotation & translation vector` is to transfer coordinate from depth camera to color camera, right? Why you use them for transforming from world coordinate??

>> would you please give me a reference for writhing `SK_rot_mx` function which should be `Rodrigues' rotation formula`?

>> second when you transfer back from network estimation to camera coordinate , why have you used just depth of root , not all coordinate of root, (`uvd2xyz function in image_uti.py`) ?

**Comment by 3d-hand-shape** [comment]
(Q1) The GT coordinates are in the depth camera's coordinate system. We transform them to coordinates in the color camera's coordinate system, and evaluate our estimation results in the color camera's coordinate system.
(Q2) Yes, we useRodrigues' rotation formula to transform the rotation vector into rotation matrix.
(Q3) the x, y coordinates of root can be computed using the estimated uv coordinates, the depth of root, and camera's intrinsic matrix.
