### ISSUE TITLE
bbox for STB

### ISSUE THREAD

**Issue by Ivamcoder** [3d-hand-shape/hand-graph-cnn#8]
Hi @3d-hand-shape 

bbox used for croping image is `Ground Truth` or is from a detector ? and reported result in paper are according `Ground Truth` hand area?

**Comment by 3d-hand-shape** [comment]
Yes, on STB dataset, we crop the hand using ground truth bounding box.

**Comment by prismformore** [comment]
How to get the GT boxes? Thank you. @Ivamcoder @3d-hand-shape
