### ISSUE TITLE
error when python eval_script.py

### ISSUE THREAD

**Issue by recoverjun** [3d-hand-shape/hand-graph-cnn#9]
hand-graph-cnn-master/hand_shape_pose/util/renderer.py", line 223
color = color_list[color_id % len(color_list)]
TypeError: 'dict_values' object does not support indexing

**Comment by 3d-hand-shape** [comment]
This is because you use Python 3, but we use Python 2. I have solved this bug by converting color_list to list type.

**Comment by recoverjun** [comment]
Thank you for your reply！I can run it's eval_script now~   i want to try the model on my own images. But i don't know the key's meaning of params.mat.   as bbox.cam_param.pose_root and pose_scale，could you teach me that？Thank you very much!❤


 
---Original---
